### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by oschrenk** [8ta4/plist#25]
Love the idea of the tool, but I am slightly hesitant to install nix, cachix, devenv, direnv to be able to build it. Is there a chance of a binary release?

**Comment by 8ta4** [comment]
I'm all for diversity, equity, and inclusion - I wish I could support both binary and non-binary releases. Sadly, we're out of luck. GitHub isn't as progressive.

GitHub Actions has Apple Silicon Macs, but they're [pricey](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/#:~:text=our%20macos%20larger%20runners%20will%20be%20priced%20at%20%240.16%2Fminute%20for%20xl%20and%20%240.12%2Fminute%20for%20large).

So, for now, I'm just playing the waiting game for GitHub Actions to get their act together.

**Comment by oschrenk** [comment]
Oh well, thanks. Maybe I can find a weekend to play around with Nix.

I hoped that you can build it locally and upload a binary to the release assets - that's free to my knowledge.

**Comment by oschrenk** [comment]
Well. Somebody listened. 

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by 8ta4** [comment]
Hearing about GitHub's M1 Mac support feels like finding out same-sex marriage just got legalized. There goes my best excuse to avoid committing.

You can install `plist` with Homebrew now.

Just run:

```sh
brew install 8ta4/plist/plist
```

Check out the prerequisites here: https://github.com/8ta4/plist/blob/2da0e202fd72f39daa43776800a3d7faae9976dc/README.md#installation

**Comment by oschrenk** [comment]
Sweet!

Unfortuantely I get

```
brew install 8ta4/plist/plist
...

plist
dyld[77594]: Library not loaded: /nix/store/s00jd00b5ar25ys72bg439msfhqbapx3-gmp-with-cxx-6.3.0/lib/libgmp.10.dylib
  Referenced from: <ABA4D88A-542F-3A74-B25F-F40A99FD7E15> /opt/homebrew/Cellar/plist/0.1.0/libexec/plist
  Reason: tried: '/nix/store/s00jd00b5ar25ys72bg439msfhqbapx3-gmp-with-cxx-6.3.0/lib/libgmp.10.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/nix/store/s00jd00b5ar25ys72bg439msfhqbapx3-gmp-with-cxx-6.3.0/lib/libgmp.10.dylib' (no such file), '/nix/store/s00jd00b5ar25ys72bg439msfhqbapx3-gmp-with-cxx-6.3.0/lib/libgmp.10.dylib' (no such file), '/usr/local/lib/libgmp.10.dylib' (no such file), '/usr/lib/libgmp.10.dylib' (no such file, not in dyld cache)
fish: Job 1, 'plist' terminated by signal SIGABRT (Abort)

```

**Comment by 8ta4** [comment]
Oops, plist was still clinging onto Nix. My bad. I've nixed Nix and switched to Homebrew's Stack. There's a new patch for you.

Give this a shot and see if it works:

```sh
brew install 8ta4/plist/plist
```

**Comment by oschrenk** [comment]
Thank you! It works now!
